# Generated by Django 2.2.16 on 2022-04-22 19:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220407_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('4959e31c-ecc7-4715-a293-c83f0c047479'), verbose_name='UUID'),
        ),
    ]
